---
- name: Install UFW package
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Reset UFW to defaults
  community.general.ufw:
    state: reset
  become: yes
  when: security_baseline_firewall_reset | default(false) | bool

- name: Set UFW default policies
  community.general.ufw:
    direction: '{{ item.direction }}'
    policy: '{{ item.policy }}'
  become: yes
  loop:
    - {
        direction: incoming,
        policy: '{{ security_baseline_firewall_default_incoming_policy }}',
      }
    - {
        direction: outgoing,
        policy: '{{ security_baseline_firewall_default_outgoing_policy }}',
      }
  notify: reload ufw

- name: Configure UFW logging
  community.general.ufw:
    logging: '{{ security_baseline_firewall_logging }}'
  become: yes

- name: Allow default ports
  community.general.ufw:
    rule: allow
    port: '{{ item.port | string }}'
    proto: "{{ item.protocol | default('tcp') }}"
    src: "{{ item.from | default('any') }}"
    comment: "{{ item.comment | default('Default rule') }}"
  become: yes
  loop: '{{ security_baseline_default_allowed_ports }}'

- name: Allow additional ports
  community.general.ufw:
    rule: allow
    port: '{{ item.port | string }}'
    proto: "{{ item.protocol | default('tcp') }}"
    src: "{{ item.from | default('any') }}"
    comment: "{{ item.comment | default('Custom rule') }}"
  become: yes
  loop: '{{ security_baseline_allowed_ports }}'
  when: security_baseline_allowed_ports | length > 0

- name: Allow specific source IPs
  community.general.ufw:
    rule: allow
    src: '{{ item.ip }}'
    port: '{{ item.port | string }}'
    proto: "{{ item.protocol | default('tcp') }}"
    comment: "{{ item.comment | default('Source-specific rule') }}"
  become: yes
  loop: '{{ security_baseline_allowed_sources }}'
  when: security_baseline_allowed_sources | length > 0

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: yes
  register: ufw_enabled
