---
# General settings
security_baseline_enabled: true
security_baseline_log_level: info

# Firewall configuration
security_baseline_firewall_enabled: true
security_baseline_firewall_default_incoming_policy: deny
security_baseline_firewall_default_outgoing_policy: allow
security_baseline_firewall_logging: 'on'
security_baseline_firewall_log_level: low

# SSH configuration
security_baseline_ssh_allow_from: 'any' # ALLOW ANY For demo only
# Default allowed ports (SSH is included by default for management)
# Format: [{ port: 80, protocol: tcp, from: any, comment: "HTTP" }]
security_baseline_default_allowed_ports:
  - {
      port: 22,
      protocol: tcp,
      from: '{{ security_baseline_ssh_allow_from }}',
      comment: 'SSH',
    }

# Additional allowed incoming ports (customize based on server role)
# Format: [{ port: 80, protocol: tcp, from: any, comment: "HTTP" }]
security_baseline_allowed_ports: []
# Allow specific source IPs (for management networks)
# Format: [{ ip: "10.0.0.0/8", port: 9999, protocol: tcp, comment: "some services all to some network" }]
security_baseline_allowed_sources: []

# Automated patching configuration
security_baseline_patching_enabled: true
security_baseline_auto_reboot: true
security_baseline_auto_reboot_time: '02:00'
security_baseline_mail_report: root
security_baseline_mail_only_on_error: true
security_baseline_apply_updates_now: true

# Unattended upgrades settings
security_baseline_allowed_origins:
  - '${distro_id}:${distro_codename}-security'
  - '${distro_id}ESMApps:${distro_codename}-apps-security'
  - '${distro_id}ESM:${distro_codename}-infra-security'

# Kernel hardening configuration
security_baseline_kernel_hardening_enabled: true
# Sysctl security parameters
security_baseline_sysctl_settings:
  # Network security - IP Spoofing protection
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  # Ignore ICMP redirects
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv6.conf.all.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  # Ignore ICMP ping requests (optional - may break monitoring)
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  # Ignore source packet routing
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv6.conf.all.accept_source_route: 0
  # Log Martians
  net.ipv4.conf.all.log_martians: 1
  # SYN flood protection
  net.ipv4.tcp_syncookies: 1
  net.ipv4.tcp_max_syn_backlog: 4096
  net.ipv4.tcp_synack_retries: 2
  net.ipv4.tcp_syn_retries: 5
  # Time-wait assassination hazards protection
  net.ipv4.tcp_rfc1337: 1
  # Disable IPv6 if not needed
  net.ipv6.conf.all.disable_ipv6: 1
  net.ipv6.conf.default.disable_ipv6: 1
  # Kernel security
  kernel.randomize_va_space: 2
  kernel.sysrq: 0
  kernel.core_uses_pid: 1
  # Hide kernel pointers
  kernel.kptr_restrict: 2
  # Restrict dmesg
  kernel.dmesg_restrict: 1
  # Restrict ptrace
  kernel.yama.ptrace_scope: 1
  # File system hardening
  fs.protected_hardlinks: 1
  fs.protected_symlinks: 1
  fs.suid_dumpable: 0
